services:
  boiler:
    build: ./
    image: boiler_publisher
    container_name: BoilerPublisher
    restart: unless-stopped
    init: true
    volumes:
      - $PWD/Store:/app/Store
    environment:
#      LOG_LEVEL: DEBUG
      HM_URL: http://192.168.12.220
      MQTT_BROKER: mqtt
      MQTT_USER: boiler
      MQTT_PASSWORD: boiler
