services:
  boiler:
    build: ./
    image: boiler_publisher
    container_name: BoilerPublisher
    restart: unless-stopped
    init: true
    volumes:
      - $PWD/Store:/app/Store
#    environment:
#      - LOGLEVEL=DEBUG
